#include <algorithm>
#include <assert.h>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <functional>
#include <iostream>
#include <netinet/in.h>
#include <stdio.h>
#include <string>
#include <sys/poll.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <fcntl.h>
#include <vector>
#include <poll.h>
#include <unistd.h>
#include "utils.h"
#include "hashtable.h"


#define PORT 8080
#define K_MAX_BUF 4096
#define K_MAX_ARGS 200*1000

struct Conn{
    int fd;
    short flags;
    std::vector<uint8_t> incoming; // data to be parsed by app
    std::vector<uint8_t> outgoing; // res generated by app
    Conn(): fd(0), flags(0), incoming({}), outgoing({}){};

};


static void fd_set_nb(int fd){
    errno = 0;
    int flags = fcntl(fd, F_GETFL, 0);
    if (errno) {
        die("fcntl:F_GETGL failed");
    }
    flags |= O_NONBLOCK;        //what is non blocking

    errno = 0;
    fcntl(fd, F_SETFL, flags);
    if (errno) {
        die("fcntl:F_SETFL failed");
    }

}

struct Conn* handle_accept(int fd){
    struct sockaddr_in client_addr;
    socklen_t client_addr_len = sizeof(client_addr);

    errno = 0;
    int connfd = accept(fd, (struct sockaddr *)&client_addr, &client_addr_len); // i don't have a understanding of what accept and socket func in client is actually doing
    //if (connfd < 0 && (errno == EAGAIN || errno == EWOULDBLOCK)) {
        //msg("listening queue empty");
        //return NULL;
    //}
    if (connfd < 0) {
        msg("Accept Failed");
        return NULL;
    }
    //uint32_t ip = ntohl(client_addr.sin_addr.s_addr);  // network to host long, still don't understand what is the need of this/ what is going on
    //fprintf(stderr, "new client from %u.%u.%u.%u:%u\n", ip>>24 & 255, ip>>16 & 255, ip>>8 & 255, ip & 255, ntohl(client_addr.sin_port));

    fd_set_nb(connfd);

    Conn *conn = new Conn();
    conn->fd = connfd;
    conn->flags |= POLLIN;

    //msg("New client connected. port:%d, addr:%d",client_addr.sin_port, client_addr.sin_addr);
    return conn;

}
void buf_append_u8(std::vector<uint8_t> &buf, const uint8_t data){
    buf.push_back(data);
}
void buf_append(std::vector<uint8_t> &buf, const uint8_t *data, size_t len){
    buf.insert(buf.end(), data, data+len);
}
void buf_append_u32(std::vector<uint8_t> &buf, const uint32_t data){
    buf_append(buf, (uint8_t*)&data, 4);
}
void buf_append_str(std::vector<uint8_t> &out, const std::string &msg){
    buf_append_u32(out, msg.size());
    buf_append(out, (uint8_t*)msg.data(), msg.size());
}
// optimization possibility - have a buffer struct, so that you just have to move the pointer instead of erase from start
void consume_buf(std::vector<uint8_t>&buf, uint32_t len){
    buf.erase(buf.begin(), buf.begin()+len);
}
static bool read_u32(const uint8_t *&cur, const uint8_t *end, uint32_t &out){
    // check if 4 bytes available
    // read 4 bytes
    if(cur + 4 > end){
        //msg("read_u32:insufficient data");
        return false;
    }
    memcpy(&out, cur, 4);
    cur += 4;
    return true;
}
static bool read_str(const uint8_t *&curr, const uint8_t *end, size_t n, std::string &out){
    if(curr + n > end){
        //msg("read_str: insufficient bytes");
        return false;
    }
    out.assign(curr, curr + n);
    curr += n;
    return true;
}
enum ResponseStatus {
    RES_OK = 0,
    RES_NX = 1,
    RES_ERR = 2,
};

static int32_t parse_req(const uint8_t *&data, const uint8_t* end, std::vector<std::string> &out){
    // if can't read uint32, return -1
    // if len of req > k_max_buf - return -1
    // read len of req times from data and store in out
    // arrangement of request in data - nstr, len1 str1, len2, str2
    // lastly check if after consuming data, there's anything still left, data != end => return -1 for trailing garbage
    // return 0
    // figured - it's always - read 4 bytes, and find how much more to read
    // so structure of message that comes = [len of total request ahead of me], [nstr = how many strings. not how many reqs], [lenstr], [str = get set del or key or new val], [lenstr],[str]
    uint32_t nstr = 0;
    if(!read_u32(data, end, nstr)){
        msg("parse_req:can't read nstr");
        return -1;
    }
    //msg("nstr:%d", nstr);
    if(nstr > K_MAX_ARGS){ // will this ever trigger, like who is taking more args than 3 anyway?
        // also no one is checking whether the initial length reported is what is being read here
        msg("parse_req:Too big request");
        return -1;
    }
    while (out.size() < nstr) {
        uint32_t len=0;
        if(!read_u32(data, end, len)){
            msg("parse_req:couldn't read len of str");
            return -1;
        }
        //msg("len:%d",len);
        out.push_back("");
        if(!read_str(data, end, (size_t)len, out.back())){
            msg("parse_req:failed to read_str");
        }
        //msg("out.back():%s", out.back().c_str());
    }
    return 0;
}

enum {
    TAG_NIL = 0,
    TAG_ERR = 1,
    TAG_STR = 2,
    TAG_INT = 3,
    TAG_DBL = 4,
    TAG_ARR = 5
};

HMap* g_data = new HMap();
struct Entry {
    HNode node;
    std::string key;
    std::string val;
};

#define container_of(ptr, T, member)    \
    ((T*)((char*)ptr - offsetof(T, member)))

bool entry_eq(HNode* lhs, HNode* rhs){
    Entry* e_lhs = container_of(lhs, Entry, node);
    Entry* e_rhs = container_of(rhs, Entry, node);
    return e_lhs->key == e_rhs->key;
}

// FNV hash
static uint64_t str_hash(const uint8_t *data, size_t len) {
    uint32_t h = 0x811C9DC5;
    for (size_t i = 0; i < len; i++) {
        h = (h + data[i]) * 0x01000193;
    }
    return h;
}

enum ERR_CODES {
    UNKNOWN_OPERATION = 0,
    MSG_TOO_BIG = 1
};

void out_nil(std::vector<uint8_t> &out){
    buf_append_u8(out, TAG_NIL);
}
void out_str(std::vector<uint8_t> &out, const std::string &str){
    buf_append_u8(out, TAG_STR);
    buf_append_str(out, str);
}
void out_int(std::vector<uint8_t> &out, uint32_t val){
    buf_append_u8(out, TAG_INT);
    buf_append_u32(out, val);
}
void out_err(std::vector<uint8_t> &out, ERR_CODES code, const std::string &msg){
    buf_append_u8(out, TAG_ERR);
    buf_append_u32(out, static_cast<uint32_t>(code));
    buf_append_str(out, msg);
}
void out_arr(std::vector<uint8_t> &out, uint32_t arr_len){
    buf_append_u8(out, TAG_ARR);
    buf_append_u32(out, arr_len);
}

void do_get(HMap* hmap, std::vector<std::string> &cmd, std::vector<uint8_t> &out){
    Entry key;
    swap(key.key, cmd[1]);
    key.node.hcode = str_hash((uint8_t*) key.key.data(), key.key.size());
    HNode* node = hm_lookup(hmap, &key.node, entry_eq);
    if(!node){
        //msg("do_request:Get Key:%s, Not Found", key.key.c_str());
        out_nil(out);
        return;
    }
    const std::string &val = container_of(node, Entry, node)->val;
    out_str(out, val);
}

void do_del(HMap* hmap, std::vector<std::string> &cmd, std::vector<uint8_t> &out){
    Entry key;
    swap(key.key, cmd[1]);
    key.node.hcode = str_hash((uint8_t*) key.key.data(), key.key.size());
    HNode* node = hm_delete(hmap, &key.node, entry_eq);
    if(!node){
        out_int(out, 0);
        return;
    }
    delete container_of(node, Entry, node);
    out_int(out, 1);
}

void do_set(HMap* hmap, std::vector<std::string> &cmd, std::vector<uint8_t> &out){
    Entry key;
    swap(key.key, cmd[1]);
    key.node.hcode = str_hash((uint8_t*) key.key.data(), key.key.size());
    HNode* node = hm_lookup(hmap, &key.node, entry_eq);
    out_nil(out);
    if(!node){
        Entry *ent = new Entry();
        ent->node.hcode = key.node.hcode;
        swap(ent->val, cmd[2]);
        swap(ent->key, key.key);
        hm_insert(hmap, &ent->node);
        return;
    }
    Entry *ent = container_of(node, Entry, node);
    swap(ent->val, cmd[2]);
}

static bool cb_keys(HNode* node, std::vector<uint8_t> &out){
    Entry* end = container_of(node, Entry, node);
    buf_append_str(out, end->key);
    return true;
}

void do_keys(HMap* hmap, std::vector<uint8_t> &out){
    out_arr(out, hm_size(hmap));
    hm_foreach(hmap, std::bind(cb_keys, std::placeholders::_1, std::ref(out)));
}

static void do_request(std::vector<std::string> &cmd, std::vector<uint8_t> &out){
    if (cmd.size() == 2 && cmd[0] == "get") {
        do_get(g_data, cmd, out);
    }
    else if (cmd.size() == 2 && cmd[0] == "del") {
        do_del(g_data, cmd, out);
    }
    else if(cmd.size() == 3 && cmd[0] == "set"){
        do_set(g_data, cmd, out);
    }
    else if(cmd.size() == 1 && cmd[0] == "keys"){
        do_keys(g_data, out);
    }
    else{
        msg("do_request:Invalid request");
        out_err(out, UNKNOWN_OPERATION, cmd[0]);
    }
}

void response_begin(std::vector<uint8_t> &out, uint32_t &header_pos){
    header_pos = out.size();
    buf_append_u32(out, 0);
}

//tag, arrlen, str1len, str1, str2len, str2
//1+4+4+2+4+2 = 17
uint32_t response_size(const std::vector<uint8_t> &out, uint32_t header_pos){
    return out.size() - header_pos - 4;
}
void response_end(std::vector<uint8_t> &out, uint32_t header_pos){
    uint32_t res_size = response_size(out, header_pos);
    if(res_size > K_MAX_BUF){
        // keeps prev response + 4 bytes for header. rejects all after that
        out.resize(header_pos + 4); 
        out_err(out, MSG_TOO_BIG, std::to_string(res_size));
        res_size = response_size(out, header_pos);
    }
    memcpy(&out[header_pos], (uint8_t*)&res_size, 4);
}
// optimization - response data goes directly to conn->outgoing
// resp - status and data

// trying to read output buf of client
// input cmd = {"get", "10"}
// output wbuf = <17,uint32> <3,uint32> <get,char[3]> <2, uint32> <10,char[3]>
bool try_one_request(Conn* conn){
    if (conn->incoming.size()==0) {
        //msg("try_one_request:conn->incoming.size()==0");
        return false; 
    }
    uint32_t req_len = 0;
    const uint8_t* data = conn->incoming.data();
    const uint8_t* end  = data + conn->incoming.size();
    if(!read_u32(data, end, req_len)){
        msg("try_one_request:couldn't read req_len");
        return false;
    }
    if(req_len > K_MAX_BUF){ // should be req_len > KMB+4
        msg("try_one_request: too big message. closing connection");
        conn->flags |= POLLERR;
        return false;
    }
    if(conn->incoming.size() < req_len+4){
        msg("try_one_request:read required. full req_len data not present");
        return false;
    }

    std::vector<std::string> cmd;
    if(parse_req(data, end, cmd) < 0){
        //msg("try_one_request:Couldn't parse request. closing connection");
        conn->flags |= POLLERR;
        return false;
    }
    uint32_t header_pos = 0;
    response_begin(conn->outgoing, header_pos);
    do_request(cmd, conn->outgoing);
    response_end(conn->outgoing, header_pos);
    consume_buf(conn->incoming, 4+req_len);
    //msg("conn->incoming.size() = ", conn->incoming.size());
    return true;
}


void handle_write(Conn* conn){
    //msg("Handling write");
    assert(conn->outgoing.size() > 0);
    ssize_t rv = write(conn->fd, conn->outgoing.data(), conn->outgoing.size());
    if (rv < 0 && errno == EAGAIN) {
        return; // not an error
    }
    if (rv < 0) {
        // error in writing
        msg_errno("Write error");
        conn->flags |= POLLERR;
        return;
    }
    //msg("Consuming write buf:size:%d, rv = %d", conn->outgoing.size(), rv);
    consume_buf(conn->outgoing, (size_t)rv);
    //msg("Consumed write buf:size:%d", conn->outgoing.size());
    if(conn->outgoing.size() == 0){
        conn->flags |= POLLIN;
        conn->flags &= ~POLLOUT;
    }
}

void handle_read(Conn* conn){
    //msg("Handling read");
    uint8_t buf[64*1024];
    errno = 0;
    ssize_t rv = read(conn->fd, buf, sizeof(buf));
    if(rv <0 && errno == EAGAIN){
        return; // not an error
    }
    if(rv < 0){
        msg_errno("Read failed");
        conn->flags &= ~POLLIN;
        conn->flags |= POLLERR;
        return;
    }
    if(rv == 0){
        if (conn->incoming.size()==0) {
            //msg("closing client");
        }
        else{
            msg_errno("Unexpected EOF"); // what if the message is fragmented and hasn't arrived yet
        }
        conn->flags |= POLLERR;
        return;
    }
    //msg("read bytes:%d", rv);

    // got some new data, put it in incoming 
    buf_append(conn->incoming, buf, (size_t)rv);

    while(try_one_request(conn)){};

    // why not conn->income.size>0 => want read more, since there is an incomplete request in the queue
    // one issue would be the too big msg.
    // is it like there can't be less than 4byte of header? ig so
    if (conn->outgoing.size()>0) {
        conn->flags &= ~POLLIN; // wrong ig
        conn->flags |= POLLOUT;
        return handle_write(conn);
    }
}

int main(){
    // the listening socket
    int fd = socket(AF_INET, SOCK_STREAM, 0);
    if (fd < 0) {
        die("Socket failed");
    }
    int val = 1;
    if(setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &val, sizeof(val))){  // why reuse addr?
        die("setsockopt Failed");
    };
    //bind
    struct sockaddr_in addr = {};
    socklen_t addrlen = sizeof(addr);
    addr.sin_family = AF_INET;
    addr.sin_port = htons(PORT);
    addr.sin_addr.s_addr = htonl(0); // wildcard = 0, same as INADDR_ANY

    int rv = bind(fd, (const struct sockaddr *)&addr, addrlen);
    if(rv){
        die("Bind failed");
    }

    // set the listen fd to nonblocking mode
    fd_set_nb(fd);


    // listen
    rv = listen(fd, SOMAXCONN); // SOMAXCONN - socket outstanding max conn
    if (rv) {
        die("listen failed");
    }
    msg("Server ready. TCP Socket. Reusing address. bind addr:%d:%d. Non Blocking mode. Listening for max:%d connections", 0, PORT, SOMAXCONN);

    std::vector<Conn * > fd2conn;
    std::vector<struct pollfd> poll_args;


    // event loop
    while (true) {
        rv = 0;
        poll_args.clear();
        poll_args.push_back({fd, POLLIN, 0});

        for (Conn* &conn : fd2conn) {
            if(!conn){
                continue;
            }
            struct pollfd pfd = {conn->fd, 0, 0};
            // events given connection is interested in
            pfd.events |= conn->flags;
            //msg("pfd.events:%d", pfd.events);
            //msg("pfd.revents:%d", pfd.revents);
            poll_args.push_back(pfd);
        }
        rv = poll(poll_args.data(), (nfds_t)poll_args.size(), -1);
        //msg("poll success:%d", rv);
        if (rv < 0 && (errno == EINTR || errno == EAGAIN)) { // interrupt sys call
            msg("Inturrupt poll call");
            continue;
        }
        if(rv < 0){
            die("poll failed");
        }
        // handle listening socket
        if(poll_args[0].revents){
            Conn *conn = handle_accept(fd); // instead of on heap, it'd better to do this on stack, since i know max conn attempts?
            if(conn){
                if (size_t(conn->fd) >= fd2conn.size()) {
                    fd2conn.resize(conn->fd + 1);
                }
                assert(!fd2conn[conn->fd]);
                fd2conn[conn->fd] = conn;
            }
        }

        // handle other connections
        for (size_t i=1; i<poll_args.size(); i++) {
            uint32_t ready = poll_args[i].revents;
            if(!ready){
                continue;
            }
            //msg("poll_args_i: %d, read_e:%d, write_e:%d, close_e:%d,read_r:%d, write_r:%d, close_r:%d", i, poll_args[i].events&POLLIN,poll_args[i].events&POLLOUT,poll_args[i].events&POLLERR ,ready&POLLIN,ready&POLLOUT,ready&POLLERR);
            Conn *conn = fd2conn[poll_args[i].fd];
            if (ready & POLLIN) {
                assert(conn->flags & POLLIN);
                handle_read(conn);
            }
            if(ready & POLLOUT){
                assert(conn->flags & POLLOUT);
                handle_write(conn);
            }
            if((ready & POLLERR) || (conn->flags & POLLERR)){
                close(conn->fd);
                fd2conn[conn->fd] = nullptr;
                delete conn;
            }
        }
    }
    rv = close(fd);
    if(rv){
        die("Close failed");
    }
    return 0;
}
